/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ErrorInfo } from '../models/errorInfo';

/**
 * Creates an instance of FaultResponse
 */
interface FaultResponse {
  /** Error report for a fatal exception. */
  fault: ErrorInfo;
}

export class FaultResponseError extends ApiError<FaultResponse> {}
