/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

/** Specifies a street address. */
export interface Address {
  /** ISO country code (3-character). */
  regionCode: string;
  /** Regional postal code or zip code. */
  postalCode: string;
  /** State or province, as a two-letter ISO or national code. */
  administrativeArea: string;
  /** City, village, or municipality name. */
  locality: string;
  /** Lines for the address itself. */
  addressLines: string[];
}

export const addressSchema: Schema<Address> = object({
  regionCode: ['regionCode', string()],
  postalCode: ['postalCode', string()],
  administrativeArea: ['administrativeArea', string()],
  locality: ['locality', string()],
  addressLines: ['addressLines', array(string())],
});
