/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { MediaItem, mediaItemSchema } from './mediaItem';
import { RasterGraphic, rasterGraphicSchema } from './rasterGraphic';

/** Asset linked to a managed brand. */
export interface BrandAsset {
  /** Rasterized asset. */
  raster?: RasterGraphic;
  /** Vector asset, if available. */
  vector?: MediaItem;
}

export const brandAssetSchema: Schema<BrandAsset> = object({
  raster: ['raster', optional(lazy(() => rasterGraphicSchema))],
  vector: ['vector', optional(lazy(() => mediaItemSchema))],
});
