/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { BrandSpec, brandSpecSchema } from './brandSpec';

/** Specifies a list of resulting Brand records. */
export interface BrandList {
  /** Array of resulting brand records. */
  brand: BrandSpec[];
}

export const brandListSchema: Schema<BrandList> = object({
  brand: ['brand', array(lazy(() => brandSpecSchema))],
});
