/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** OpenCannabis color specification. */
export interface Color {
  /** Specifies a color in hex. */
  hex: string;
}

export const colorSchema: Schema<Color> = object({ hex: ['hex', string()] });
