/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema';
import { Phone, phoneSchema } from './phone';

/** Contact information. */
export interface Contact {
  /** Phone number. */
  phone: Phone;
  /** Assigned email domain. */
  domain: string;
}

export const contactSchema: Schema<Contact> = object({
  phone: ['phone', lazy(() => phoneSchema)],
  domain: ['domain', string()],
});
