/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { MediaItem, mediaItemSchema } from './mediaItem';

/** Asset which is capable of specifying both a vector and raster form of a given asset. */
export interface DualFormatGraphic {
  /** Raster version of this graphic. */
  raster?: MediaItem;
  /** Vector version of this graphic. */
  vector?: MediaItem;
}

export const dualFormatGraphicSchema: Schema<DualFormatGraphic> = object({
  raster: ['raster', optional(lazy(() => mediaItemSchema))],
  vector: ['vector', optional(lazy(() => mediaItemSchema))],
});
