/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Detailed information about an error. */
export interface ErrorDetail {
  /** Specifies an error code or well-qualified error path. */
  errorcode: string;
}

export const errorDetailSchema: Schema<ErrorDetail> = object({
  errorcode: ['errorcode', string()],
});
