/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { ErrorDetail, errorDetailSchema } from './errorDetail';

/** Information describing an error that occurred while transacting with the API. */
export interface ErrorInfo {
  /** Describes the error with a readable label or message. */
  faultstring: string;
  /** Further info about the error. */
  detail?: ErrorDetail;
}

export const errorInfoSchema: Schema<ErrorInfo> = object({
  faultstring: ['faultstring', string()],
  detail: ['detail', optional(lazy(() => errorDetailSchema))],
});
