/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema } from '../schema';
import { CookiesBrandEnum, cookiesBrandEnumSchema } from './cookiesBrandEnum';

/** Specifies first party branding for a store or other entity. */
export interface FirstPartyBranding {
  /** Specifies a first-party brand owned or operated by Cookies. */
  brand: CookiesBrandEnum;
}

export const firstPartyBrandingSchema: Schema<FirstPartyBranding> = object({
  brand: ['brand', cookiesBrandEnumSchema],
});
