/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

/** Geo point or boundary information. */
export interface Geo {
  /** Latitude value for a geo point. */
  latitude: number;
  /** Longitude value for a geo point. */
  longitude: number;
}

export const geoSchema: Schema<Geo> = object({
  latitude: ['latitude', number()],
  longitude: ['longitude', number()],
});
