/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, Schema } from '../schema';
import { StoreStatusEnum, storeStatusEnumSchema } from './storeStatusEnum';
import { TimeSpec, timeSpecSchema } from './timeSpec';

/** Range/interval of hours. */
export interface HoursRange {
  /** Begin time for a given hours range. */
  begin: TimeSpec;
  /** End time for a given hours range. */
  end: TimeSpec;
  /** Status to apply for a store. */
  status: StoreStatusEnum;
  /** Whether this hours rule is active. */
  active: boolean;
}

export const hoursRangeSchema: Schema<HoursRange> = object({
  begin: ['begin', lazy(() => timeSpecSchema)],
  end: ['end', lazy(() => timeSpecSchema)],
  status: ['status', storeStatusEnumSchema],
  active: ['active', boolean()],
});
