/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { RegularHours, regularHoursSchema } from './regularHours';

/** Describes regular and special store hours. */
export interface Hours {
  /** Specifies regular store hours. */
  regular: RegularHours[];
}

export const hoursSchema: Schema<Hours> = object({
  regular: ['regular', array(lazy(() => regularHoursSchema))],
});
