/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Describes material or operational regarding about a Cookies strain. */
export interface MaterialInfo {
  /** Breeder(s) who produced a strain. */
  breeder?: string;
  /** Aroma notes for a strain. */
  aroma?: string;
  /** Flavor notes for a strain. */
  flavor?: string;
  /** Experience notes for a strain. */
  experience?: string;
}

export const materialInfoSchema: Schema<MaterialInfo> = object({
  breeder: ['breeder', optional(string())],
  aroma: ['aroma', optional(string())],
  flavor: ['flavor', optional(string())],
  experience: ['experience', optional(string())],
});
