/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { MediaKey, mediaKeySchema } from './mediaKey';
import { MediaType, mediaTypeSchema } from './mediaType';

/** Reference to a known media asset. */
export interface MediaItem {
  /** Unique key assigned to, or generated for, this asset. */
  key: MediaKey;
  /** Type specifications for this asset. */
  type?: MediaType;
  /** Serving URI, if available, for this asset. */
  servingUri?: string;
  /** Origin URI for this asset. */
  uri?: string;
}

export const mediaItemSchema: Schema<MediaItem> = object({
  key: ['key', lazy(() => mediaKeySchema)],
  type: ['type', optional(lazy(() => mediaTypeSchema))],
  servingUri: ['servingUri', optional(string())],
  uri: ['uri', optional(string())],
});
