/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Generic name, with an alternative label. */
export interface Name {
  /** Display label. */
  label?: string;
  /** Alternate display label. */
  alt?: string;
  /** Primary name. */
  primary?: string;
  /** Display name for this record. Overrides all other names. */
  display?: string;
}

export const nameSchema: Schema<Name> = object({
  label: ['label', optional(string())],
  alt: ['alt', optional(string())],
  primary: ['primary', optional(string())],
  display: ['display', optional(string())],
});
