/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Social media account property. */
export interface SocialProperty {
  /** Social network where this profile exists. */
  property: string;
  /** Link to this social profile. */
  link?: string;
  /** Unique ID for this social profile, or username. */
  id?: string;
}

export const socialPropertySchema: Schema<SocialProperty> = object({
  property: ['property', string()],
  link: ['link', optional(string())],
  id: ['id', optional(string())],
});
