/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema, string } from '../schema';
import { SocialProperty, socialPropertySchema } from './socialProperty';

/** Social media information for a first-party Cookies store. */
export interface StoreSocial {
  /** Social media properties. */
  property: SocialProperty[];
  /** Store Facebook page username. */
  facebookUser: string;
}

export const storeSocialSchema: Schema<StoreSocial> = object({
  property: ['property', array(lazy(() => socialPropertySchema))],
  facebookUser: ['facebookUser', string()],
});
