/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Store, storeSchema } from './store';

/** Describes a list of store records. */
export interface StoreList {
  /** List of stores. */
  store: Store[];
}

export const storeListSchema: Schema<StoreList> = object({
  store: ['store', array(lazy(() => storeSchema))],
});
