/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Specifies key information which uniquely identifies a physical retail store. */
export interface StoreKey {
  /** Unique ID for a store. */
  id: string;
  /** First-party store code. */
  code: string;
}

export const storeKeySchema: Schema<StoreKey> = object({
  id: ['id', string()],
  code: ['code', string()],
});
