/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { CookiesBrandEnum, cookiesBrandEnumSchema } from './cookiesBrandEnum';

/** Specifies request details when listing stores. */
export interface StoresRequest {
  /** Optionally filter stores by first-party brand. */
  brand?: CookiesBrandEnum;
}

export const storesRequestSchema: Schema<StoresRequest> = object({
  brand: ['brand', optional(cookiesBrandEnumSchema)],
});
