/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { MediaItem, mediaItemSchema } from './mediaItem';

/** Photography and other media related to a first-party Cookies store. */
export interface StoreMedia {
  /** Facade photography of a Cookies store. */
  facade: MediaItem[];
  /** Inside photography of a Cookies store. */
  inside: MediaItem[];
  /** Masthead (featured) photography for a Cookies store. */
  masthead: MediaItem[];
}

export const storeMediaSchema: Schema<StoreMedia> = object({
  facade: ['facade', array(lazy(() => mediaItemSchema))],
  inside: ['inside', array(lazy(() => mediaItemSchema))],
  masthead: ['masthead', array(lazy(() => mediaItemSchema))],
});
