/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StoreStatusEnum
 */
export enum StoreStatusEnum {
  OPEN = 'OPEN',
  CLOSED = 'CLOSED',
  PICKUPONLY = 'PICKUP_ONLY',
  DELIVERYONLY = 'DELIVERY_ONLY',
}

/**
 * Schema for StoreStatusEnum
 */
export const storeStatusEnumSchema: Schema<StoreStatusEnum> = stringEnum(StoreStatusEnum);
