/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

/** Web information for a Cookies store, or partner store. */
export interface StoreWeb {
  /** Main website link. */
  main: string;
}

export const storeWebSchema: Schema<StoreWeb> = object({
  main: ['main', string()],
});
