/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema';
import { Strain, strainSchema } from './strain';

/** Describes a list of Cookies strain records. */
export interface StrainList {
  /** Array of resulting strain records. */
  strain: Strain[];
}

export const strainListSchema: Schema<StrainList> = object({
  strain: ['strain', array(lazy(() => strainSchema))],
});
