/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema';

/** Describes social media properties for a given strain. */
export interface StrainSocial {
  /** Count of available reviews for this strain. */
  reviewCount: number;
  /** Average rating for this strain, across available public reviews. */
  reviewRating: number;
}

export const strainSocialSchema: Schema<StrainSocial> = object({
  reviewCount: ['reviewCount', number()],
  reviewRating: ['reviewRating', number()],
});
