/**
 * Cookies APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Color, colorSchema } from './color';

/** OpenCannabis record which describes theming information for a given record. */
export interface Theme {
  /** Primary color. */
  primary?: Color;
  /** Secondary color. */
  secondary?: Color;
  /** Alert color. */
  alert?: Color;
}

export const themeSchema: Schema<Theme> = object({
  primary: ['primary', optional(lazy(() => colorSchema))],
  secondary: ['secondary', optional(lazy(() => colorSchema))],
  alert: ['alert', optional(lazy(() => colorSchema))],
});
